# Generated by Django 3.0.7 on 2020-06-14 08:31

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Stu_Info',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('classes', models.CharField(max_length=20)),
                ('major', models.CharField(max_length=25)),
                ('information', models.TextField()),
                ('deeds', models.TextField()),
                ('is_nominated', models.BooleanField(default=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('votes', models.IntegerField(default=0)),
                ('submit_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('last_update_time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
