# Generated by Django 3.0.7 on 2020-06-14 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CurriculumDesign', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='stu_info',
            name='ip',
            field=models.CharField(default='127.0.0.1', max_length=16),
        ),
    ]
