# Generated by Django 3.0.7 on 2020-06-15 10:42

from django.db import migrations, models
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('CurriculumDesign', '0002_stu_info_ip'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='stu_info',
            managers=[
                ('object', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterField(
            model_name='stu_info',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
