# Generated by Django 3.0.7 on 2020-06-17 08:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('IPRECORD', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Stu_Info',
            new_name='IPRECORD',
        ),
    ]
